language: nix

cache: false


before_install:
 - unset CC

install:

script:
 - git clone https://github.com/reflex-frp/reflex-platform
 - cd reflex-platform && sudo echo "Yes" | ./try-reflex --command "exit 0"
 - strace nix build -f ../release.nix servant-reflex

 - nix build -f ./release.nix servant-reflex --substituters https://cache.nixos.org --substituters https://nixcache.reflex-frp.org
 - nix build -f ./release.nix testresults
 - git config --global user.email "travis-ci@example.com"
 - git config --global user.name "Travis-CI"

cache:
  directories:
  - /nix
  - $HOME/.cabal/packages
  - $HOME/.cabal/store

env:
  global:
    - ENCRYPTION_LABEL: "3c89d919c82e"
    - COMMIT_AUTHOR_EMAIL: "imalsogreg@gmail.com"
