language: nix
nix: 2.3.6
sudo: require

before_install:
  - sudo cp -rT $TRAVIS_BUILD_DIR/nix /etc/nix

before_script:
  - sudo systemctl restart nix-daemon.service
  - git config --global user.email "travis-ci@example.com"
  - git config --global user.name "Travis-CI"

script:
  - nix-build travis.nix -A build
  - nix-build travis.nix -A buildGhc
  - nix-build travis.nix -A testserver
  - nix-build travis.nix -A testresults
